//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNTB.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserInfo
    {
        public int UserInfoId { get; set; }
        public string FullName { get; set; }
        public string avatar { get; set; }
        public string Position { get; set; }
        public string CompanyName { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Addresss { get; set; }
        public string Servicee { get; set; }
        public int TaxCode { get; set; }
        public string Banking_1 { get; set; }
        public string Banking_2 { get; set; }
        public string FaceBook { get; set; }
        public int Zalo { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
